version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: svoyskae-backend
    hostname: svoyskae-backend
    working_dir: /backend
    command: npm run start:prod
    restart: always
    ports:
    - 5000:5000
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
